/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nxp_facemanager_Oasis */

#ifndef _Included_com_nxp_facemanager_Oasis
#define _Included_com_nxp_facemanager_Oasis
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nxp_facemanager_Oasis
 * Method:    faceRecognize
 * Signature: ([BII[B[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nxp_facemanager_Oasis_faceRecognize
  (JNIEnv *, jobject, jbyteArray, jint, jint, jintArray, jint, jintArray, jbyteArray, jintArray,
          jobjectArray, jintArray);

/*
 * Class:     com_nxp_facemanager_Oasis
 * Method:    faceAdd
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_com_nxp_facemanager_Oasis_faceAdd__
  (JNIEnv *, jobject, jstring, jbyteArray);
/*
 * Class:     com_nxp_facemanager_Oasis
 * Method:    faceDel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_nxp_facemanager_Oasis_faceDel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nxp_facemanager_Oasis
 * Method:    faceDelAll
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nxp_facemanager_Oasis_faceDelAll
  (JNIEnv *, jobject);

/*
 * Class:     com_nxp_facemanager_Oasis
 * Method:    Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nxp_facemanager_Oasis_Init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nxp_facemanager_Oasis
 * Method:    Exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nxp_facemanager_Oasis_Exit
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL
Java_com_nxp_facemanager_Oasis_cancelOp(JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif